name: cezeri_helper
description: "Gemeinsame Widgets & Konstanten für Flutter Projekte - UI Components, Shopify API Integration und nützliche Utilities"
version: 0.0.4
homepage: https://github.com/aliince/cezeri_helper
repository: https://github.com/aliince/cezeri_helper

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  alerter: ^1.0.2
  auto_route: ^10.1.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  email_validator: ^3.0.0
  equatable: ^2.0.7
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_dropzone: ^4.2.1
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_widget_from_html: ^0.17.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  graphql_flutter: ^5.2.1
  http: ^1.5.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  mime: ^2.0.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  photo_view: ^0.15.0
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4
  wolt_modal_sheet: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1

flutter:
  generate: true

  assets:
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Regular.ttf
